### ISSUE TITLE
[bug] Error when using plugin on waterfall

### ISSUE THREAD

**Issue by Tobi-Jakka** [xxneox/EpicGuard#107]
### Bug from console:
https://paste.gg/p/anonymous/6ba20d6d240d49e8a618b93ee64d092c

### Server info:
![image](https://user-images.githubusercontent.com/42676160/132103548-979a7172-8bde-4d79-bc84-cb282486373d.png)
![image](https://user-images.githubusercontent.com/42676160/132103563-0f7fed1f-c3cf-4191-a537-5c9d03cbcce6.png)

Version of EpicGuard I used:
![image](https://user-images.githubusercontent.com/42676160/132104195-853afb47-58dc-41d4-bd63-0f4ce663a6a3.png)
(latest)

**Comment by xxneox** [comment]
Have you changed the plugin's storage method to MySQL or are you using the default setting of SQLite?

**Comment by Tobi-Jakka** [comment]
Not yet, this was on the first load up, lemme do that though

**Comment by Tobi-Jakka** [comment]
replaced the data (dont worry will make a new database so credentiels dont matter)
![image](https://user-images.githubusercontent.com/42676160/132104471-c32c2268-cc4a-44e1-80c4-3030ffc76089.png)

got this error which is prob because the password isnt in a string?
https://paste.gg/p/anonymous/c97dc739c8154e178f4eb1650c014fce

**Comment by xxneox** [comment]
> https://paste.gg/p/anonymous/c97dc739c8154e178f4eb1650c014fce

Yes, the parser error says that these values needs to be enclosed in quotes, just like the host value.

The first error is because the SQLite drivers are missing in Bungeecord, i will just need to include them in the jar. Not sure if the MySQL drivers are missing too.

**Comment by Tobi-Jakka** [comment]
I see, I didnt use quotes because the default config didnt have that..

So I should put quotes around database, password, port & user?

**Comment by Tobi-Jakka** [comment]
also got a new error from doing that:
https://paste.gg/p/anonymous/2036b28ebd594ac185c557f3c3fdfe12

**Comment by xxneox** [comment]
Okay, so MySQL driver is present (the error is because there is probably no mysql server running on 127.0.0.1).
I assume you will just use the default option of SQLite, so download a new build which should be available in a few minutes.

**Comment by Tobi-Jakka** [comment]
ohh I just noticed I used wrong host I will try changing to the proper ip my bad it looked similar

**Comment by Tobi-Jakka** [comment]
it started up without errors...

**Comment by Tobi-Jakka** [comment]
Well I guess 1 thing I will ask is if you would put quotes around password & user for mysql in the default config?

**Comment by xxneox** [comment]
Yeah i can do that. So the issue is resolved now?

**Comment by Tobi-Jakka** [comment]
Yes, issue resolved. Thanks :)
