### ISSUE TITLE
[Bug] "Could not save data to the SQL database."

### ISSUE THREAD

**Issue by Tobi-Jakka** [xxneox/EpicGuard#110]
### Error from console: (on shutdown)
https://paste.gg/p/anonymous/333c642ae65a41c4824e7095ab2ab947

EDIT: also happens after some time (not sure how long / what caused it):
https://paste.gg/p/anonymous/8ae609cd10734843ae9fa12a0e5f1ea5

I tried making a new clean database but this still happens...

**Comment by xxneox** [comment]
Should be fixed in the latest release

**Comment by Tobi-Jakka** [comment]
Issue is fixed. Thanks :)

Btw I would like to add that you are one of the most active devs I have seen in a while, is there somewhere where I can donate to this project?

- Tobi

**Comment by Tobi-Jakka** [comment]
Also seems like a new error appeared in console after some time: https://paste.gg/p/anonymous/d94046c31a6c450c90e8567fc7185bce
@xxneox

**Comment by xxneox** [comment]
This is a different issue, just fixed it (no need to update or anything, this error won't show anymore)

**Comment by Tobi-Jakka** [comment]
Yes I can confirm that there have been no errors since, thanks :)
