### ISSUE TITLE
[Feature Request] Add captcha

### ISSUE THREAD

**Issue by Memexurer** [xxneox/EpicGuard#118]
dodaj captche pls fajnie bedzie wtedy
:trollface:

**Comment by rusekhdev** [comment]
ok

**Comment by Memexurer** [comment]
jaki kurwa future request autysto xddd

**Comment by Memexurer** [comment]
sory no offense

**Comment by rusekhdev** [comment]
> jaki kurwa future request autysto xddd

nwm przyszłe żądanie

**Comment by Slddev** [comment]
+1

**Comment by Memexurer** [comment]
nie chce mi sie robic tego EZ
