### ISSUE TITLE
MySQL data storage not working with MariaDB

### ISSUE THREAD

**Issue by cloakfox** [xxneox/EpicGuard#135]
Hey,

I was trying to setup mysql data storage instead of sqlite but ran into these errors after configuration
https://gist.github.com/cloakfox/584178e2df5c490411b31f67540e19e3

This server is running Airplane version git-Airplane-103 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 86fee6b on HEAD)

(Fork of Paper)

Maybe im doing something wrong, but the config looks good on my end.

**Comment by xxneox** [comment]
MariaDB support has been fixed in the dev builds, try the latest: https://github.com/xxneox/EpicGuard/suites/4420927391/artifacts/116920796

**Comment by cloakfox** [comment]
> MariaDB support has been fixed in the dev builds, try the latest: https://github.com/xxneox/EpicGuard/suites/4420927391/artifacts/116920796

Just tried the build you linked in your reply, but it can't seem to load it with plugman. I've not had issues with that before with this plugin, I can try a server restart later.

**Comment by xxneox** [comment]
Yeah, i changed rewrote the whole storage system so i guess it can't be just reloaded on runtime with plugman. But it works with a normal restart. Btw just released 7.1.1
