### ISSUE TITLE
Console Filter Suggestion

### ISSUE THREAD

**Issue by notperry1** [xxneox/EpicGuard#65]
You should add a option called something like "filter-only-on-bot-attack" or something similar which means it just only puts on the  filter when a attack happens cause with console filter on it will just always hide the join msgs in console and not only when there's a attack which is a minor annoyance not any major issue but just suggesting sense i saw this option on botsentry.

**Comment by xxneox** [comment]
Thank you for your suggestion! I have added the "console-filter-mode" setting which allows to enable console-filter only on attack or disable it fully. It will be available in the next release.
