### ISSUE TITLE
Error while starting EpicGuard 7.0.0 in Velocity 3.0.x

### ISSUE THREAD

**Issue by 4drian3d** [xxneox/EpicGuard#98]
An error occurs when starting EpicGuard 7.0.0 in Velocity 3.0.1 https://pastebin.com/PSz7Vb3B

Java Version: openjdk version "16.0.1"
Velocity Version: 
> velocity version
> [12:01:43 INFO]: Velocity 3.0.1-SNAPSHOT (git-adcf428e-bunknown)

**Comment by xxneox** [comment]
Try the latest build

**Comment by 4drian3d** [comment]
Now the plugin starts correctly, thanks
